-- phpMyAdmin SQL Dump
-- version 3.4.5deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 20, 2011 at 04:44 PM
-- Server version: 5.1.58
-- PHP Version: 5.3.6-13ubuntu3.2

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `opentaps`
--

-- --------------------------------------------------------

--
-- Table structure for table `projects`
--

CREATE TABLE IF NOT EXISTS `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `unique` int(11) NOT NULL,
  `lang` varchar(50) NOT NULL,
  `title` varchar(200) NOT NULL,
  `description` text NOT NULL,
  `beneficiary_people` varchar(255) NOT NULL,
  `budget` int(10) NOT NULL,
  `city` varchar(100) NOT NULL,
  `grantee` varchar(255) NOT NULL,
  `sector` varchar(255) NOT NULL,
  `start_at` date NOT NULL,
  `end_at` date NOT NULL,
  `info` text NOT NULL,
  `type` varchar(255) NOT NULL,
  `place_unique` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=50 ;

--
-- Dumping data for table `projects`
--

INSERT INTO `projects` (`id`, `unique`, `lang`, `title`, `description`, `beneficiary_people`, `budget`, `city`, `grantee`, `sector`, `start_at`, `end_at`, `info`, `type`, `place_unique`) VALUES
(15, 1, 'ka', 'Water Pollution Fixing in Rustavi', 'Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.', '', 6230000, 'Rustavi', 'Ministry of Pain', '42nd international battle station', '2012-12-05', '2013-04-03', 'Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.', 'Water Pollution', 1),
(16, 2, 'ka', 'Sewage in Batumi', '<p>Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.</p>', '', 13235000, 'Batumi', 'Random grantee', 'Random sector', '2005-10-10', '2010-07-08', '<p>Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.</p>', 'Sewage', 2),
(17, 3, 'ka', 'Sewage in Batumi', 'Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.', '', 13235000, 'Batumi', 'Random grantee', 'Random sector', '2005-10-10', '2010-07-08', 'Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.', 'Sewage', 3),
(18, 1, 'en', 'Water Pollution Fixing in Rustavi (en)', 'Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.', '', 6230000, 'Rustavi', 'Ministry of Pain', '42nd international battle station', '2012-12-05', '2013-04-03', 'Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.', 'Water Pollution', 1),
(19, 2, 'en', 'Sewage in Batumi', 'Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.', '', 13235000, 'Batumi', 'Random grantee', 'Random sector', '2005-10-10', '2010-07-08', 'Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.', 'Sewage', 2),
(20, 3, 'en', 'Sewage in Batumi', 'Criminal law, also known as penal law, pertains to crimes and punishment.[21] It thus regulates the definition of and penalties for offences found to have a sufficiently deleterious social impact but, in itself, makes no moral judgment on an offender nor imposes restrictions on society that physically prevents people from committing a crime in the first place.[22] Investigating, apprehending, charging, and trying suspected offenders is regulated by the law of criminal procedure.[23] The paradigm case of a crime lies in the proof, beyond reasonable doubt, that a person is guilty of two things. First, the accused must commit an act which is deemed by society to be criminal, or actus reus (guilty act).[24] Second, the accused must have the requisite malicious intent to do a criminal act, or mens rea (guilty mind). However for so called "strict liability" crimes, an actus reus is enough.[25] Criminal systems of the civil law tradition distinguish between intention in the broad sense (dolus directus and dolus eventualis), and negligence. Negligence does not carry criminal responsibility unless a particular crime provides for its punishment.', '', 13235000, 'Batumi', 'Random grantee', 'Random sector', '2005-10-10', '2010-07-08', 'Legal systems elaborate rights and responsibilities in a variety of ways. A general distinction can be made between civil law jurisdictions, which codify their laws, and common law systems, where judge made law is not consolidated. In some countries, religion informs the law. Law provides a rich source of scholarly inquiry, into legal history, philosophy, economic analysis or sociology. Law also raises important and complex issues concerning equality, fairness and justice. "In its majestic equality", said the author Anatole France in 1894, "the law forbids rich and poor alike to sleep under bridges, beg in the streets and steal loaves of bread."[5] In a typical democracy, the central institutions for interpreting and creating law are the three main branches of government, namely an impartial judiciary, a democratic legislature, and an accountable executive.', 'Sewage', 3),
(38, 6, 'en', '33333333', '<p>33333333</p>', '', 33333333, '33333333', '33333333', '33333333', '1000-10-10', '1994-06-10', '<p>33333333</p>', 'Sewage', 4),
(36, 5, 'en', '33333333', '<p>33333333333333333333333</p>', '', 2147483647, '333333333333333', '3333333333333333', '33333', '3333-11-11', '3333-12-11', '<p>333333333333333333333333333</p>', 'Sewage', 4),
(37, 5, 'ka', '33333333', '<p>33333333333333333333333</p>', '', 2147483647, '333333333333333', '3333333333333333', '33333', '3333-11-11', '3333-12-11', '<p>333333333333333333333333333</p>', 'Water Supply', 4),
(32, 4, 'en', 'lockdown ', '<p>lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown v</p>', '', 43673373, 'lockdown ', 'lockdown ', 'lockdown 3', '3333-11-11', '1000-10-10', '<p>lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;</p>', 'Sewage', 1),
(33, 4, 'ka', 'lockdown ', '<p>lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown v</p>', '', 43673373, 'lockdown ', 'lockdown ', 'lockdowna', '3333-11-11', '1000-10-10', '<p>lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;lockdown&nbsp;</p>', 'Water Accidents', 2),
(39, 6, 'ka', '33333333', '<p>33333333</p>', '', 33333333, '33333333', '33333333', '33333333', '1000-10-10', '1994-06-10', '<p>33333333</p>', 'Irrigation', 4),
(40, 7, 'en', 'ტესტა', '', '', 0, '', '', '', '0000-00-00', '0000-00-00', '', 'Sewage', 5),
(41, 7, 'ka', 'ტესტა', '', '', 0, 'Tbilisi', 'g ts', 's t', '2010-02-03', '2222-00-00', '', 'Water Accidents', 2447),
(42, 8, 'en', 'asdasda', '', '', 0, '', '', '', '0000-00-00', '0000-00-00', '', 'Sewage', 4),
(43, 8, 'ka', 'wWWWWWWW', '', '', 0, 'asd', '', '', '0000-00-00', '0000-00-00', '', 'Sewage', 4),
(49, 9, 'ka', 'testp', '', '', 0, '', '', '', '0000-00-00', '0000-00-00', '', 'Sewage', 1),
(48, 9, 'en', 'testp (en)', '', '', 0, '', '', '', '0000-00-00', '0000-00-00', '', 'Sewage', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
